server:
  port: 7901

spring:
  druid:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    #最大连接数
    max-active: 30
    min-idle: 5
    max-wait: 10000
    validation-query: SELECT 'x'
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
  application:
    name: microservice-provider-user
#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#日志配置 file指日志文件的相对位置
logging:
#  控制台日志
#  pattern:
#    console: "%d - %msg%n"
  level:
    org:
      springframework:
       web: debug

#暴露服务
eureka:
  client:
   service-url:
     defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true